### ISSUE TITLE
Panic from /check

### ISSUE THREAD

**Issue by vito** [dpb587/bosh-release-resource#2]
Hi there, first off - this is an awesome resource! Really cool to see how it automates versioning of BOSH dev releases - no more manually versioning and uploading a ton of release candidates into a bucket over time. Cool that you're experimenting with redistributable tasks, too - more motivation for https://github.com/concourse/rfcs/issues/7.

Anyhow - I'm using it for our [new pipeline](https://ci.concourse-ci.org/teams/main/pipelines/concourse?groups=bosh), however it seems to panic during the `/check` call now. It's still finding versions somehow (maybe it's flaky?), but the check error says:

```
resource script '/opt/resource/check []' failed: exit status 2

stderr:
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/dpb587/bosh-release-resource/boshrelease.Repository.GetCommitList(0xc4200a22c0, 0x33, 0x0, 0x0, 0xc4200a2380, 0x3a, 0x0, 0x0, 0xc4200140b2, 0x7, ...)
	/go/src/github.com/dpb587/bosh-release-resource/boshrelease/repository.go:198 +0x7fd
github.com/dpb587/bosh-release-resource/boshrelease.Release.DevVersions(0xc42001a4c0, 0xc4200828a0, 0xc420018ab0, 0x9, 0xc4200140b2, 0x7, 0x4, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/dpb587/bosh-release-resource/boshrelease/release.go:47 +0xa2
main.main()
	/go/src/github.com/dpb587/bosh-release-resource/check/main.go:66 +0x209
```

Here's my resource config:

```yaml
resources:
- name: concourse-release
  type: bosh-release
  source:
    uri: https://github.com/concourse/concourse-bosh-release
    dev_releases: true
    private_config:
      blobstore:
        provider: gcs
        options:
          credentials_source: static
          json_key: ((concourse_artifacts_json_key))
```

If I run the `git log --format=%h %ci`, as the resource is doing, I see this at the very end:

```
# ... snipped ...
f329935 2014-04-27 16:11:22 -0700
730a938 2014-04-27 16:11:01 -0700
c99ac1a 2014-04-27 15:35:04 -0700

~
```

Not sure what's with that blank line and `~`, but I guess that's what it's choking on.
